### ISSUE TITLE
Updates to Becoming-a-Chocolatier-with-PowerShell.md

### ISSUE THREAD

**Issue by ferventcoder** [alexinslc/alexinslc-chocolatey-packages#1]
Looks like you need -y after the commands now.
The new templating is included with choco as `choco new`. This allows you to remove the warmup and chocolateytemplate sections.

You could probably include a link to automatic packages versus restating most of the automatic package information.

**Comment by alexinslc** [comment]
Thanks! I'll make these changes shortly.

**Comment by alexinslc** [comment]
All better. Just simplified and added more links to the original documentation.
